const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    getConfig: () => ipcRenderer.invoke('get-config'),
    saveConfig: (cfg) => ipcRenderer.invoke('save-config', cfg),
    startAgents: () => ipcRenderer.invoke('start-agents'),
    stopAgents: () => ipcRenderer.invoke('stop-agents'),
    getStatus: () => ipcRenderer.invoke('get-status'),
    openProject: (p) => ipcRenderer.invoke('open-project', p),
    readTodo: (p) => ipcRenderer.invoke('read-todo', p),
    readDone: (p) => ipcRenderer.invoke('read-done', p),
    saveTodo: (p, c) => ipcRenderer.invoke('save-todo', p, c),
    readGeneratedTasks: (p) => ipcRenderer.invoke('read-generated-tasks', p),
    approveGeneratedTasks: (p) => ipcRenderer.invoke('approve-generated-tasks', p),
    analyzeProject: (p) => ipcRenderer.invoke('analyze-project', p),
    readProjectReport: (p) => ipcRenderer.invoke('read-project-report', p),
    readPinnedKnowledge: (p) => ipcRenderer.invoke('read-pinned-knowledge', p),
    savePinnedKnowledge: (p, items) => ipcRenderer.invoke('save-pinned-knowledge', p, items),
    detectDuplicateTask: (p, text) => ipcRenderer.invoke('detect-duplicate-task', p, text),
    readReviewSummary: (p) => ipcRenderer.invoke('read-review-summary', p),
    readApplyCandidates: (p) => ipcRenderer.invoke('read-apply-candidates', p),
    listSprints: (p) => ipcRenderer.invoke('list-sprints', p),
    readCurrentSprint: (p) => ipcRenderer.invoke('read-current-sprint', p),
    createSprint: (p, selectedTasks) => ipcRenderer.invoke('create-sprint', p, selectedTasks),
    analyzeBuildLogs: (p) => ipcRenderer.invoke('analyze-build-logs', p),
    readBuildDiagnostics: (p) => ipcRenderer.invoke('read-build-diagnostics', p),
    generateVerticalSlicePlan: (p) => ipcRenderer.invoke('generate-vertical-slice-plan', p),
    readVerticalSlicePlan: (p) => ipcRenderer.invoke('read-vertical-slice-plan', p),
    generateVerticalSliceStatus: (p) => ipcRenderer.invoke('generate-vertical-slice-status', p),
    readVerticalSliceStatus: (p) => ipcRenderer.invoke('read-vertical-slice-status', p),
    generateGameState: (p) => ipcRenderer.invoke('generate-game-state', p),
    readGameState: (p) => ipcRenderer.invoke('read-game-state', p),
    generateCommandCenter: (p) => ipcRenderer.invoke('generate-command-center', p),
    readCommandCenter: (p) => ipcRenderer.invoke('read-command-center', p),
    generatePmValidation: (p) => ipcRenderer.invoke('generate-pm-validation', p),
    readPmValidation: (p) => ipcRenderer.invoke('read-pm-validation', p),
    approveCommandCenterTasks: (p) => ipcRenderer.invoke('approve-command-center-tasks', p),
    parseCommandRecommendations: (p) => ipcRenderer.invoke('parse-command-recommendations', p),
    approveSelectedCommandTasks: (p, ids) => ipcRenderer.invoke('approve-selected-command-tasks', p, ids),
    generatePatchCandidates: (p) => ipcRenderer.invoke('generate-patch-candidates', p),
    readPatchCandidates: (p) => ipcRenderer.invoke('read-patch-candidates', p),
    generateTraceability: (p) => ipcRenderer.invoke('generate-traceability', p),
    readTraceability: (p) => ipcRenderer.invoke('read-traceability', p),
    generatePlayLoopTemplate: (p) => ipcRenderer.invoke('generate-play-loop-template', p),
    readPlayLoopTemplate: (p) => ipcRenderer.invoke('read-play-loop-template', p),
    generateCodeCandidates: (p) => ipcRenderer.invoke('generate-code-candidates', p),
    generateCodeCandidate: (p, templateId) => ipcRenderer.invoke('generate-code-candidate', p, templateId),
    listCodeTemplates: () => ipcRenderer.invoke('list-code-templates'),
    promoteCandidateToProject: (p, candidateFile) => ipcRenderer.invoke('promote-candidate-to-project', p, candidateFile),
    generateImplementationTrace: (p) => ipcRenderer.invoke('generate-implementation-trace', p),
    readImplementationTrace: (p) => ipcRenderer.invoke('read-implementation-trace', p),
    generateProjectInventory: (p) => ipcRenderer.invoke('generate-project-inventory', p),
    readProjectInventory: (p) => ipcRenderer.invoke('read-project-inventory', p),
    getActualOnlyProgress: (p) => ipcRenderer.invoke('get-actual-only-progress', p),
    registerApplyCandidate: (p, candidateFile) => ipcRenderer.invoke('register-apply-candidate', p, candidateFile),
    readApplyQueue: (p) => ipcRenderer.invoke('read-apply-queue', p),
    approveApplyQueue: (p, queueFile) => ipcRenderer.invoke('approve-apply-queue', p, queueFile),
    rejectApplyQueue: (p, queueFile) => ipcRenderer.invoke('reject-apply-queue', p, queueFile),
    runApplyDryRun: (p, queueFile) => ipcRenderer.invoke('run-apply-dry-run', p, queueFile),
    onLog: (cb) => ipcRenderer.on('log', (_, d) => cb(d)),
    onAgentUpdate: (cb) => ipcRenderer.on('agent-update', (_, d) => cb(d)),
    onStatsUpdate: (cb) => ipcRenderer.on('stats-update', (_, d) => cb(d)),
    onStatusChange: (cb) => ipcRenderer.on('status-change', (_, d) => cb(d)),
    onCycleUpdate: (cb) => ipcRenderer.on('cycle-update', (_, d) => cb(d)),
    onAllDone: (cb) => ipcRenderer.on('all-done', (_, d) => cb(d)),
    onGeneratedTasksUpdate: (cb) => ipcRenderer.on('generated-tasks-update', (_, d) => cb(d)),
    onApplyCandidatesUpdate: (cb) => ipcRenderer.on('apply-candidates-update', (_, d) => cb(d)),
    minimize: () => ipcRenderer.send('window-minimize'),
    maximize: () => ipcRenderer.send('window-maximize'),
    close: () => ipcRenderer.send('window-close'),
});
