const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    getConfig: () => ipcRenderer.invoke('get-config'),
    saveConfig: (cfg) => ipcRenderer.invoke('save-config', cfg),
    startAgents: () => ipcRenderer.invoke('start-agents'),
    stopAgents: () => ipcRenderer.invoke('stop-agents'),
    getStatus: () => ipcRenderer.invoke('get-status'),
    openProject: (p) => ipcRenderer.invoke('open-project', p),
    readTodo: (p) => ipcRenderer.invoke('read-todo', p),
    readDone: (p) => ipcRenderer.invoke('read-done', p),
    saveTodo: (p, c) => ipcRenderer.invoke('save-todo', p, c),
    readGeneratedTasks: (p) => ipcRenderer.invoke('read-generated-tasks', p),
    approveGeneratedTasks: (p) => ipcRenderer.invoke('approve-generated-tasks', p),
    analyzeProject: (p) => ipcRenderer.invoke('analyze-project', p),
    readProjectReport: (p) => ipcRenderer.invoke('read-project-report', p),
    readPinnedKnowledge: (p) => ipcRenderer.invoke('read-pinned-knowledge', p),
    savePinnedKnowledge: (p, items) => ipcRenderer.invoke('save-pinned-knowledge', p, items),
    detectDuplicateTask: (p, text) => ipcRenderer.invoke('detect-duplicate-task', p, text),
    readReviewSummary: (p) => ipcRenderer.invoke('read-review-summary', p),
    readApplyCandidates: (p) => ipcRenderer.invoke('read-apply-candidates', p),
    listSprints: (p) => ipcRenderer.invoke('list-sprints', p),
    readCurrentSprint: (p) => ipcRenderer.invoke('read-current-sprint', p),
    createSprint: (p, selectedTasks) => ipcRenderer.invoke('create-sprint', p, selectedTasks),
    analyzeBuildLogs: (p) => ipcRenderer.invoke('analyze-build-logs', p),
    readBuildDiagnostics: (p) => ipcRenderer.invoke('read-build-diagnostics', p),
    generateVerticalSlicePlan: (p) => ipcRenderer.invoke('generate-vertical-slice-plan', p),
    readVerticalSlicePlan: (p) => ipcRenderer.invoke('read-vertical-slice-plan', p),
    generateVerticalSliceStatus: (p) => ipcRenderer.invoke('generate-vertical-slice-status', p),
    readVerticalSliceStatus: (p) => ipcRenderer.invoke('read-vertical-slice-status', p),
    generateGameState: (p) => ipcRenderer.invoke('generate-game-state', p),
    readGameState: (p) => ipcRenderer.invoke('read-game-state', p),
    generateCommandCenter: (p) => ipcRenderer.invoke('generate-command-center', p),
    readCommandCenter: (p) => ipcRenderer.invoke('read-command-center', p),
    generatePmValidation: (p) => ipcRenderer.invoke('generate-pm-validation', p),
    readPmValidation: (p) => ipcRenderer.invoke('read-pm-validation', p),
    approveCommandCenterTasks: (p) => ipcRenderer.invoke('approve-command-center-tasks', p),
    parseCommandRecommendations: (p) => ipcRenderer.invoke('parse-command-recommendations', p),
    approveSelectedCommandTasks: (p, ids) => ipcRenderer.invoke('approve-selected-command-tasks', p, ids),
    generatePatchCandidates: (p) => ipcRenderer.invoke('generate-patch-candidates', p),
    readPatchCandidates: (p) => ipcRenderer.invoke('read-patch-candidates', p),
    generateTraceability: (p) => ipcRenderer.invoke('generate-traceability', p),
    readTraceability: (p) => ipcRenderer.invoke('read-traceability', p),
    generatePlayLoopTemplate: (p) => ipcRenderer.invoke('generate-play-loop-template', p),
    readPlayLoopTemplate: (p) => ipcRenderer.invoke('read-play-loop-template', p),
    generateCodeCandidates: (p) => ipcRenderer.invoke('generate-code-candidates', p),
    generateCodeCandidate: (p, templateId) => ipcRenderer.invoke('generate-code-candidate', p, templateId),
    listCodeTemplates: () => ipcRenderer.invoke('list-code-templates'),
    promoteCandidateToProject: (p, candidateFile) => ipcRenderer.invoke('promote-candidate-to-project', p, candidateFile),
    generateImplementationTrace: (p) => ipcRenderer.invoke('generate-implementation-trace', p),
    readImplementationTrace: (p) => ipcRenderer.invoke('read-implementation-trace', p),
    generateProjectInventory: (p) => ipcRenderer.invoke('generate-project-inventory', p),
    readProjectInventory: (p) => ipcRenderer.invoke('read-project-inventory', p),
    getActualOnlyProgress: (p) => ipcRenderer.invoke('get-actual-only-progress', p),
    registerApplyCandidate: (p, candidateFile) => ipcRenderer.invoke('register-apply-candidate', p, candidateFile),
    readApplyQueue: (p) => ipcRenderer.invoke('read-apply-queue', p),
    createApplyReview: (p, queueFile) => ipcRenderer.invoke('create-apply-review', p, queueFile),
    readApplyReviews: (p) => ipcRenderer.invoke('read-apply-reviews', p),
    generateApplyReviewWorkflowReport: (p) => ipcRenderer.invoke('generate-apply-review-workflow-report', p),
    listApprovedApplyCandidates: (p) => ipcRenderer.invoke('list-approved-apply-candidates', p),
    createUE5ImportManifest: (p, candidateFile) => ipcRenderer.invoke('create-ue5-import-manifest', p, candidateFile),
    createUE5ImportManifestsFromApproved: (p) => ipcRenderer.invoke('create-ue5-import-manifests-from-approved', p),
    readUE5ImportManifests: (p) => ipcRenderer.invoke('read-ue5-import-manifests', p),
    generateUE5ImportManifestReport: (p) => ipcRenderer.invoke('generate-ue5-import-manifest-report', p),
    approveApplyQueue: (p, queueFile) => ipcRenderer.invoke('approve-apply-queue', p, queueFile),
    rejectApplyQueue: (p, queueFile) => ipcRenderer.invoke('reject-apply-queue', p, queueFile),
    runApplyDryRun: (p, queueFile) => ipcRenderer.invoke('run-apply-dry-run', p, queueFile),
    // V67-V72: Image-to-3D Pipeline
    scanAssetInputImages: (p) => ipcRenderer.invoke('scan-asset-input-images', p),
    generateImageDecompositionPlan: (p, intakeFile) => ipcRenderer.invoke('generate-image-decomposition-plan', p, intakeFile),
    generateSegment3DJobs: (p, decompositionFile) => ipcRenderer.invoke('generate-segment-3d-jobs', p, decompositionFile),
    runAssetQualityGate: (p) => ipcRenderer.invoke('run-asset-quality-gate', p),
    runImageTo3DDryRun: (p) => ipcRenderer.invoke('run-image-to-3d-dry-run', p),
    openAssetImagesFolder: (p) => ipcRenderer.invoke('open-asset-images-folder', p),
    readAssetQualityReport: (p) => ipcRenderer.invoke('read-asset-quality-report', p),
    getAssetPipelineSummary: (p) => ipcRenderer.invoke('get-asset-pipeline-summary', p),
    // V78: 3D Inspector 판정 + Apply Candidate
    create3DInspectionRecord:        (p, d) => ipcRenderer.invoke('create-3d-inspection-record', p, d),
    list3DInspectionRecords:         (p)    => ipcRenderer.invoke('list-3d-inspection-records', p),
    read3DInspectionRecord:          (p, f) => ipcRenderer.invoke('read-3d-inspection-record', p, f),
    get3DInspectionSummary:          (p)    => ipcRenderer.invoke('get-3d-inspection-summary', p),
    generate3DInspectionReport:      (p)    => ipcRenderer.invoke('generate-3d-inspection-report', p),
    promote3DInspectionToCandidate:  (p, f) => ipcRenderer.invoke('promote-3d-inspection-to-candidate', p, f),
    // V77: 환경 점검 시스템
    getEnvironmentStatus:       ()          => ipcRenderer.invoke('get-environment-status'),
    detectGpu:                  ()          => ipcRenderer.invoke('detect-gpu'),
    checkProviderCompatibility: (provider)  => ipcRenderer.invoke('check-provider-compatibility', provider),
    detectProviderInstallation: (provider)  => ipcRenderer.invoke('detect-provider-installation', provider),
    runPreflightChecks:         (p)         => ipcRenderer.invoke('run-preflight-checks', p),
    // V76: 3D Generator Manager — 무료 로컬 3D 생성 AI
    loadAssetGeneratorConfig:  ()          => ipcRenderer.invoke('load-asset-generator-config'),
    saveAssetGeneratorConfig:  (cfg)       => ipcRenderer.invoke('save-asset-generator-config', cfg),
    getAssetGeneratorStatus:   (p)         => ipcRenderer.invoke('get-asset-generator-status', p),
    build3DGenerationCommand:  (jobFile,p) => ipcRenderer.invoke('build-3d-generation-command', jobFile, p),
    runLocal3DGenerator:       (jobFile,p) => ipcRenderer.invoke('run-local-3d-generator', jobFile, p),
    detectGenerated3DAssets:   (p)         => ipcRenderer.invoke('detect-generated-3d-assets', p),
    write3DGenerationLog:      (p,content) => ipcRenderer.invoke('write-3d-generation-log', p, content),
    dryRun3DGeneration:        (jobFile,p) => ipcRenderer.invoke('dry-run-3d-generation', jobFile, p),
    // V75: 3D Inspector — 읽기 전용 에셋 뷰어
    listGeneratedAssets: (p) => ipcRenderer.invoke('list-generated-assets', p),
    read3dFile: (filePath, p) => ipcRenderer.invoke('read-3d-file', filePath, p),
    // V74: Knowledge Agent — 자동 기억 시스템
    buildKnowledgeContext: (p, query) => ipcRenderer.invoke('build-knowledge-context', p, query),
    recordAgentMemory: (p, entry) => ipcRenderer.invoke('record-agent-memory', p, entry),
    recordDecision: (p, decision, detail) => ipcRenderer.invoke('record-decision', p, decision, detail),
    generateKnowledgeSummary: (p) => ipcRenderer.invoke('generate-knowledge-summary', p),
    getAgentMemory: (p) => ipcRenderer.invoke('get-agent-memory', p),
    getProjectDecisions: (p) => ipcRenderer.invoke('get-project-decisions', p),
    // V73: Knowledge Agent — Obsidian Vault
    getVaultStatus: (p) => ipcRenderer.invoke('vault-status', p),
    scanVault: (p) => ipcRenderer.invoke('scan-vault', p),
    searchVault: (p, query) => ipcRenderer.invoke('search-vault', p, query),
    readVaultNote: (p, notePath) => ipcRenderer.invoke('read-vault-note', p, notePath),
    getRelatedNotes: (p, topic) => ipcRenderer.invoke('get-related-notes', p, topic),
    createVaultNote: (p, folder, title, content, tags) => ipcRenderer.invoke('create-vault-note', p, folder, title, content, tags),
    updateVaultNote: (p, notePath, content, overwrite) => ipcRenderer.invoke('update-vault-note', p, notePath, content, overwrite),
    getRecentNotes: (p, limit) => ipcRenderer.invoke('get-recent-notes', p, limit),
    getVaultSummary: (p) => ipcRenderer.invoke('get-vault-summary', p),
    // V62-V65: Existing Project Awareness
    scanExistingProject: (p) => ipcRenderer.invoke('scan-existing-project', p),
    readExistingProjectInventory: (p) => ipcRenderer.invoke('read-existing-project-inventory', p),
    findExistingImplementation: (p, systemName) => ipcRenderer.invoke('find-existing-implementation', p, systemName),
    validateCandidateAgainstProject: (p, candidateFile) => ipcRenderer.invoke('validate-candidate-against-project', p, candidateFile),
    generateExtensionCandidate: (p, systemName, spec) => ipcRenderer.invoke('generate-extension-candidate', p, systemName, spec),
    onLog: (cb) => ipcRenderer.on('log', (_, d) => cb(d)),
    onAgentUpdate: (cb) => ipcRenderer.on('agent-update', (_, d) => cb(d)),
    onStatsUpdate: (cb) => ipcRenderer.on('stats-update', (_, d) => cb(d)),
    onStatusChange: (cb) => ipcRenderer.on('status-change', (_, d) => cb(d)),
    onCycleUpdate: (cb) => ipcRenderer.on('cycle-update', (_, d) => cb(d)),
    onAllDone: (cb) => ipcRenderer.on('all-done', (_, d) => cb(d)),
    onGeneratedTasksUpdate: (cb) => ipcRenderer.on('generated-tasks-update', (_, d) => cb(d)),
    onApplyCandidatesUpdate: (cb) => ipcRenderer.on('apply-candidates-update', (_, d) => cb(d)),
    minimize: () => ipcRenderer.send('window-minimize'),
    maximize: () => ipcRenderer.send('window-maximize'),
    close: () => ipcRenderer.send('window-close'),
});
